import os
import re
import sqlite3
from urllib.parse import urlparse

DATABASE_URL = os.getenv("DATABASE_URL", "")
DB_PATH = os.path.join(os.path.dirname(__file__), "cygnal.db")

is_pg = bool(DATABASE_URL)
pg_pool = None

if is_pg:
    try:
        from psycopg2.pool import SimpleConnectionPool
        result = urlparse(DATABASE_URL)
        username = result.username
        password = result.password
        database = result.path[1:]
        hostname = result.hostname
        port = result.port or 5432
        
        pg_pool = SimpleConnectionPool(
            1, 20,
            user=username,
            password=password,
            host=hostname,
            port=port,
            database=database
        )
        print("[DB_UTILS] Initialized PostgreSQL connection pool successfully.")
    except Exception as e:
        print("[DB_UTILS] Failed to initialize PostgreSQL connection pool, falling back to SQLite:", str(e))
        is_pg = False

class DialectCursor:
    def __init__(self, cursor, is_pg_mode):
        self.cursor = cursor
        self.is_pg = is_pg_mode

    def execute(self, sql, params=None):
        if self.is_pg:
            # 1. Replace placeholder ? with %s
            sql = sql.replace("?", "%s")
            
            # 2. Translate SQLite date/time functions to PostgreSQL
            sql = re.sub(r"DATETIME\('now'\)", "CURRENT_TIMESTAMP", sql, flags=re.IGNORECASE)
            sql = re.sub(r"DATETIME\(\s*'now'\s*\)", "CURRENT_TIMESTAMP", sql, flags=re.IGNORECASE)
            
            # 3. Translate SQLite AUTOINCREMENT and other dialects for initial setup
            sql = re.sub(r"AUTOINCREMENT", "GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.IGNORECASE)
            
            # 4. Handle PRAGMA checks translation if executed directly
            if "PRAGMA table_info" in sql:
                table_name = re.findall(r"table_info\((.*?)\)", sql, re.IGNORECASE)
                if table_name:
                    tbl = table_name[0].strip().replace("'", "").replace('"', "")
                    # Query PG information_schema to return column names in format mimicking sqlite table_info:
                    # SQLite PRAGMA table_info returns rows: (cid, name, type, notnull, dflt_value, pk)
                    sql = """
                        SELECT 0 as cid, column_name as name, data_type as type, 
                               CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END as notnull,
                               column_default as dflt_value,
                               CASE WHEN column_name = 'id' THEN 1 ELSE 0 END as pk
                        FROM information_schema.columns 
                        WHERE table_name = %s;
                    """
                    params = (tbl,)

        if params is not None:
            if not isinstance(params, (tuple, list)):
                params = (params,)
            self.cursor.execute(sql, params)
        else:
            self.cursor.execute(sql)
        return self

    def executemany(self, sql, params_list):
        if self.is_pg:
            sql = sql.replace("?", "%s")
            sql = re.sub(r"DATETIME\('now'\)", "CURRENT_TIMESTAMP", sql, flags=re.IGNORECASE)
        self.cursor.executemany(sql, params_list)
        return self

    def fetchone(self):
        return self.cursor.fetchone()

    def fetchall(self):
        return self.cursor.fetchall()

    def __getattr__(self, name):
        return getattr(self.cursor, name)

class DialectConnection:
    def __init__(self, conn, is_pg_mode, pool=None):
        self.conn = conn
        self.is_pg = is_pg_mode
        self.pool = pool

    def cursor(self):
        return DialectCursor(self.conn.cursor(), self.is_pg)

    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()

    def close(self):
        if self.is_pg and self.pool:
            try:
                self.pool.putconn(self.conn)
            except Exception:
                self.conn.close()
        else:
            self.conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()

def get_db_connection():
    if is_pg and pg_pool:
        try:
            conn = pg_pool.getconn()
            conn.autocommit = False
            return DialectConnection(conn, True, pg_pool)
        except Exception as e:
            print("[DB_UTILS] Failed to get connection from pool, trying direct connection:", str(e))
    
    conn = sqlite3.connect(DB_PATH)
    return DialectConnection(conn, False)
